name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "~/app"

      - name: Replace config on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p ~/app/config
          echo '${{ secrets.DEFAULT_JSON }}' > ~/app/config/default.json
          echo '${{ secrets.PRODUCTION_JSON }}' > ~/app/config/production.json

      - name: Run docker on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          timeout: 1200s
          command_timeout: 1200s
          script: |
            cd ~/app
            docker stop app || true
            docker rm app || true
            docker image rm app-image || true
            docker system prune -af --volumes
            docker build -t app-image .
            docker run -d -p 3000:3000 --name tg_bot --rm tg_bot
